# Generated by Django 4.1.5 on 2023-01-30 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('urgente', models.BooleanField(default=False)),
                ('municipio', models.CharField(max_length=50)),
                ('parroquia', models.CharField(max_length=50)),
                ('referido', models.CharField(max_length=50)),
                ('ci_referido', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_n', models.DateField(blank=True, null=True)),
                ('lugar_n', models.CharField(max_length=100)),
                ('est_civil', models.CharField(choices=[('S', 'Soltera'), ('C', 'Casada'), ('D', 'Divorciada'), ('V', 'Viuda')], default='S', max_length=1)),
                ('direccion', models.CharField(max_length=50)),
                ('sabe_leer_escribir', models.BooleanField(default=True)),
                ('ocupacion', models.CharField(max_length=100)),
                ('nombre_apellido_f', models.CharField(max_length=150)),
                ('edad_f', models.IntegerField(blank=True, null=True)),
                ('ci', models.IntegerField(blank=True, null=True)),
                ('est_civil_f', models.CharField(choices=[('S', 'Soltera'), ('C', 'Casada'), ('D', 'Divorciada'), ('V', 'Viuda')], default='S', max_length=1)),
                ('ocupacion_f', models.CharField(max_length=100)),
                ('parades', models.CharField(max_length=50)),
                ('piso', models.CharField(max_length=50)),
                ('techo', models.CharField(max_length=50)),
                ('cuartos', models.IntegerField(blank=True, null=True)),
                ('comedor', models.BooleanField(default=True)),
                ('sala', models.BooleanField(default=True)),
                ('cocina', models.BooleanField(default=True)),
                ('sueldo', models.IntegerField(blank=True, null=True)),
                ('subsidios', models.IntegerField(blank=True, null=True)),
                ('becas_pen_jub', models.IntegerField(blank=True, null=True)),
                ('ayudas_familiares', models.IntegerField(blank=True, null=True)),
                ('otros', models.IntegerField(blank=True, null=True)),
                ('total_ingresos', models.IntegerField(blank=True, null=True)),
                ('vivienda', models.IntegerField(blank=True, null=True)),
                ('servicios', models.IntegerField(blank=True, null=True)),
                ('transporte', models.IntegerField(blank=True, null=True)),
                ('medicinas', models.IntegerField(blank=True, null=True)),
                ('total_egresos', models.IntegerField(blank=True, null=True)),
                ('enf_padecidas', models.CharField(max_length=200)),
                ('enf_actuales', models.CharField(max_length=200)),
                ('medico_tratante', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('observaciones', models.TextField(max_length=1000)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
